[tool.ruff]
select = ["ALL"]
line-length = 200
ignore = [
    "ANN001",  # Missing type annotation for function argument
    "ANN201",  # Missing return type annotation for public function
    "ANN202",  # Missing return type annotation for private function `_construct_thread_context`
    "ANN204",  # Missing return type annotation for special method `__init__`
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D107",    # Missing docstring in `__init__`
    "E501",    # Line too long
    "G004",    # Logging statement uses f-string
    "S603",    # `subprocess` call: check for execution of untrusted input
    "TD002",   # Missing author in TODO
    "TD003",   # Missing issue link for this TODO
]
