name: format-recipes

on:
  push:
    branches:
      - main
    paths:
      - 'recipes/**/*.draft.md'
  workflow_dispatch:

jobs:
  format-recipes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Create formatted recipe versions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd py
          poetry run python3 src/format_recipes.py

      - name: Commit and push changes
        uses: ./.github/actions/commit-and-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "recipes/**/*.formatted.md"
          message: "Add formatted recipe versions"
