name: test-workflow

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry deps
        uses: ./.github/actions/setup-python-environment

      - name: Run tests
        run: poetry run python3 scripts/test_workflow.py
