name: Update README.md

on:
  push:
    branches:
      - main
    paths:
      - recipes.json
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python Scripts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install -r scripts/requirements.txt
          python3 scripts/generate_readme.py

      - name: Commit and push changes
        env:
          COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
          COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --local user.email "${COMMIT_USER_EMAIL}"
          git config --local user.name "${COMMIT_USER_NAME}"
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin main
          git add README.md
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Update README.md"
            git push origin main
          fi
