name: Update README with Recipes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          echo "# Kochbuch" > README.md
          echo "" >> README.md
          for file in *.md; do
            if [[ "$file" == "README.md" ]]; then
              continue
            fi
            if [[ "$file" == .* ]] || [[ "$file" == \$* ]]; then
              continue
            fi
            title="${file%.md}"
            echo "- ($title)[$file]" >> README.md
          done

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: Update README.md with recipes
          github-token: ${{ secrets.GITHUB_TOKEN }}
