name: update-readme-md

on:
  push:
    branches:
      - main
    paths:
      - recipes.json
  workflow_run:
    workflows:
      - "update-recipes-json"
    types:
      - completed
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Update README.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python3 py/src/update_readme.py

      - name: Commit and push changes
        uses: ./.github/actions/commit-and-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "README.md"
          message: "Update README.md"
