name: update-recipes-json

on:
  push:
    branches:
      - main
    paths:
      - recipes/**
  workflow_dispatch:

jobs:
  update-recipes-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Collect Recipes
        run: |
          poetry run python3 py/src/collect_recipes.py

      - name: Add Emojis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python3 py/src/add_emojis.py

      - name: Commit and push changes
        uses: ./.github/actions/commit-and-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "recipes.json"
          message: "Update recipes.json"
